name: Publish

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: codeberg-tiny
    steps:
      - uses: actions/checkout@v6

      - run: |
          mkdir tmp
          cp *.css tmp/

      - uses: actions/git-pages@v2
        with:
          site: 'https://${{ forge.event.repository.owner.username }}.codeberg.page/${{ forge.event.repository.name }}/'
          token: ${{ forge.token }}
          source: tmp/
